### PR TITLE
Upgrade to scala 2.12

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Hi Chris

As we're moving over to Scala 2.12, I needed this dependency to be compatible. Let me know if this looks good for you 😃

### CODE REVIEW

**Comment by cb372** [comment]
LGTM. I'll release when I'm in front of a computer.

**Comment by cb372** [comment]
Actually it looks like Travis only ran the build for Scala 2.11.x. Would you mind sorting that out?

**Comment by regiskuckaertz** [comment]
Oops, done. Thanks for checking 👍

**Comment by cb372** [comment]
Published as 0.2 for Scala 2.11 and 2.12. Thanks for the contribution!

**Comment by regiskuckaertz** [comment]
Nice! You're welcome.

**Pull request merged**
